CREATE TABLE `LIBRA`.`RAW_TRANSACTION`
(
    `GC_GUID`       BIGINT      NOT NULL,
    `SOURCE_ID`     BIGINT      NULL,
    `RAW_RECORD`    TEXT        NULL,
    `SEQUENCE`      BIGINT      NOT NULL,
    `MSG_ID`        VARCHAR(100),
    `VERSION`       INT         NOT NULL,
    `DUPLICATE_FLG` INT         NOT NULL,
    `CREATED_AT`    TIMESTAMP   NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`    VARCHAR(30) NULL,
    `CREATED_FROM`  VARCHAR(30) NULL,
    `UPDATED_AT`    TIMESTAMP   NULL
        ON UPDATE CURRENT_TIMESTAMP,
    `UPDATED_BY`    VARCHAR(30),
    `UPDATED_FROM`  VARCHAR(30) NULL,
    PRIMARY KEY (`GC_GUID`),
    INDEX `RAW_TRANSACTION_NX1` (`CREATED_AT` DESC)
)
    ENGINE = InnoDB;

CREATE TABLE `LIBRA`.`GOLD_COPY_TRANSACTION`
(
    `GC_GUID`             BIGINT      NOT NULL,
    `SOURCE_ID`           BIGINT      NULL,
    `SEQUENCE`            INT,
    `COMPOSITE_UNIQUE_ID` VARCHAR(40),
    `SSB_ASSET_ID`        VARCHAR(40),
    `SSB_TRADE_ID`        VARCHAR(40),
    `FUND_ID`             VARCHAR(10),
    `TRANS_TYPE`          VARCHAR(10),
    `SOURCE_SYSTEM_ID`    VARCHAR(40),

    `CR_CCY_BASE`         VARCHAR(6),
    `CR_ACCT_ID`          VARCHAR(20),
    `CR_ACCT_OFFICE`      VARCHAR(10),
    `CR_TRANS_AMOUNT`     DECIMAL(25, 6),
    `CR_CHECK`            VARCHAR(10),
    `CR_TRANS_TYPE`       VARCHAR(10),
    `CR_TRANS_RSN_CD`     VARCHAR(10),
    `CR_VALUE_DATE`       TIMESTAMP(40),
    `CR_RSN_CD`           VARCHAR(10),

    `DR_CCY_BASE`         VARCHAR(6),
    `DR_ACCT_ID`          VARCHAR(20),
    `DR_ACCT_OFFICE`      VARCHAR(10),
    `DR_TRANS_AMOUNT`     DECIMAL(25, 6),
    `DR_CHECK`            VARCHAR(10),
    `DR_TRANS_TYPE`       VARCHAR(10),
    `DR_TRANS_RSN_CD`     VARCHAR(10),
    `DR_VALUE_DATE`       TIMESTAMP(40),
    `DR_RSN_CD`           VARCHAR(10),

    `REFERENCE_ID`        VARCHAR(40),
    `RELATED_REFERENCE`   VARCHAR(40),
    `TRANS_DESC`          VARCHAR(100),


    `CREATED_AT`          TIMESTAMP   NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`          VARCHAR(30) NULL DEFAULT CURRENT_USER,
    `CREATED_FROM`        VARCHAR(30) NULL DEFAULT CURRENT_USER,
    `UPDATED_AT`          TIMESTAMP   NULL
        ON UPDATE CURRENT_TIMESTAMP,
    `UPDATED_BY`          VARCHAR(20) NULL,
    `UPDATED_FROM`        VARCHAR(20) NULL,
    PRIMARY KEY (`GC_GUID`),
    INDEX `RAW_TRANSACTION_NX1` (`CREATED_AT` DESC)
)
    ENGINE = InnoDB;