// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RawTransaction.proto

package com.ivyxjc.libra.core.models.protoModels;

public final class ProtoRawTransaction {
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    java.lang.String[] descriptorData = {
            "\n\024RawTransaction.proto\022(com.ivyxjc.libra" +
                    ".core.models.protoModels\"V\n\017PRawTransact" +
                    "ion\022\020\n\010sourceId\030\001 \001(\005\022\020\n\010sequence\030\002 \001(\005\022" +
                    "\014\n\004guid\030\003 \001(\t\022\021\n\trawRecord\030\004 \001(\tB\025B\023Prot" +
                    "oRawTransactionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    });
    internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor,
            new java.lang.String[]{"SourceId", "Sequence", "Guid", "RawRecord",});
  }

  private ProtoRawTransaction() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface PRawTransactionOrBuilder extends
          // @@protoc_insertion_point(interface_extends:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sourceId = 1;</code>
     *
     * @return The sourceId.
     */
    int getSourceId();

    /**
     * <code>int32 sequence = 2;</code>
     *
     * @return The sequence.
     */
    int getSequence();

    /**
     * <code>string guid = 3;</code>
     *
     * @return The guid.
     */
    java.lang.String getGuid();

    /**
     * <code>string guid = 3;</code>
     *
     * @return The bytes for guid.
     */
    com.google.protobuf.ByteString
    getGuidBytes();

    /**
     * <code>string rawRecord = 4;</code>
     *
     * @return The rawRecord.
     */
    java.lang.String getRawRecord();

    /**
     * <code>string rawRecord = 4;</code>
     *
     * @return The bytes for rawRecord.
     */
    com.google.protobuf.ByteString
    getRawRecordBytes();
  }

  /**
   * Protobuf type {@code com.ivyxjc.libra.core.models.protoModels.PRawTransaction}
   */
  public static final class PRawTransaction extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
          PRawTransactionOrBuilder {
    public static final int SOURCEID_FIELD_NUMBER = 1;
    public static final int SEQUENCE_FIELD_NUMBER = 2;
    public static final int GUID_FIELD_NUMBER = 3;
    public static final int RAWRECORD_FIELD_NUMBER = 4;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
    private static final com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<PRawTransaction>
            PARSER = new com.google.protobuf.AbstractParser<PRawTransaction>() {
      @java.lang.Override
      public PRawTransaction parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new PRawTransaction(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction();
    }

    private int sourceId_;
    private int sequence_;
    private volatile java.lang.Object guid_;
    private volatile java.lang.Object rawRecord_;
    private byte memoizedIsInitialized = -1;

    // Use PRawTransaction.newBuilder() to construct.
    private PRawTransaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private PRawTransaction() {
      guid_ = "";
      rawRecord_ = "";
    }

    private PRawTransaction(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sourceId_ = input.readInt32();
              break;
            }
            case 16: {

              sequence_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              guid_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              rawRecord_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<PRawTransaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new PRawTransaction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.class, com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.Builder.class);
    }

    /**
     * <code>int32 sourceId = 1;</code>
     * @return The sourceId.
     */
    public int getSourceId() {
      return sourceId_;
    }

    /**
     * <code>int32 sequence = 2;</code>
     * @return The sequence.
     */
    public int getSequence() {
      return sequence_;
    }

    /**
     * <code>string guid = 3;</code>
     * @return The guid.
     */
    public java.lang.String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        guid_ = s;
        return s;
      }
    }

    /**
     * <code>string guid = 3;</code>
     * @return The bytes for guid.
     */
    public com.google.protobuf.ByteString
    getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string rawRecord = 4;</code>
     * @return The rawRecord.
     */
    public java.lang.String getRawRecord() {
      java.lang.Object ref = rawRecord_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rawRecord_ = s;
        return s;
      }
    }

    /**
     * <code>string rawRecord = 4;</code>
     * @return The bytes for rawRecord.
     */
    public com.google.protobuf.ByteString
    getRawRecordBytes() {
      java.lang.Object ref = rawRecord_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        rawRecord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (sourceId_ != 0) {
        output.writeInt32(1, sourceId_);
      }
      if (sequence_ != 0) {
        output.writeInt32(2, sequence_);
      }
      if (!getGuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, guid_);
      }
      if (!getRawRecordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rawRecord_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sourceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, sourceId_);
      }
      if (sequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(2, sequence_);
      }
      if (!getGuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, guid_);
      }
      if (!getRawRecordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rawRecord_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction)) {
        return super.equals(obj);
      }
      com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction other = (com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction) obj;

      if (getSourceId()
              != other.getSourceId()) return false;
      if (getSequence()
              != other.getSequence()) return false;
      if (!getGuid()
              .equals(other.getGuid())) return false;
      if (!getRawRecord()
              .equals(other.getRawRecord())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
      hash = (53 * hash) + getSourceId();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
      hash = (37 * hash) + GUID_FIELD_NUMBER;
      hash = (53 * hash) + getGuid().hashCode();
      hash = (37 * hash) + RAWRECORD_FIELD_NUMBER;
      hash = (53 * hash) + getRawRecord().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PRawTransaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.ivyxjc.libra.core.models.protoModels.PRawTransaction}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
            com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransactionOrBuilder {
      private int sourceId_;
      private int sequence_;
      private java.lang.Object guid_ = "";
      private java.lang.Object rawRecord_ = "";

      // Construct using com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.class, com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        sourceId_ = 0;

        sequence_ = 0;

        guid_ = "";

        rawRecord_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
      }

      @java.lang.Override
      public com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction getDefaultInstanceForType() {
        return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.getDefaultInstance();
      }

      @java.lang.Override
      public com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction build() {
        com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction buildPartial() {
        com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction result = new com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction(this);
        result.sourceId_ = sourceId_;
        result.sequence_ = sequence_;
        result.guid_ = guid_;
        result.rawRecord_ = rawRecord_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction) {
          return mergeFrom((com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction other) {
        if (other == com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.getDefaultInstance())
          return this;
        if (other.getSourceId() != 0) {
          setSourceId(other.getSourceId());
        }
        if (other.getSequence() != 0) {
          setSequence(other.getSequence());
        }
        if (!other.getGuid().isEmpty()) {
          guid_ = other.guid_;
          onChanged();
        }
        if (!other.getRawRecord().isEmpty()) {
          rawRecord_ = other.rawRecord_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>int32 sourceId = 1;</code>
       * @return The sourceId.
       */
      public int getSourceId() {
        return sourceId_;
      }

      /**
       * <code>int32 sourceId = 1;</code>
       * @param value The sourceId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceId(int value) {

        sourceId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 sourceId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceId() {

        sourceId_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>int32 sequence = 2;</code>
       * @return The sequence.
       */
      public int getSequence() {
        return sequence_;
      }

      /**
       * <code>int32 sequence = 2;</code>
       * @param value The sequence to set.
       * @return This builder for chaining.
       */
      public Builder setSequence(int value) {

        sequence_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 sequence = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequence() {

        sequence_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>string guid = 3;</code>
       * @return The guid.
       */
      public java.lang.String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string guid = 3;</code>
       * @param value The guid to set.
       * @return This builder for chaining.
       */
      public Builder setGuid(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        guid_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string guid = 3;</code>
       * @return The bytes for guid.
       */
      public com.google.protobuf.ByteString
      getGuidBytes() {
        java.lang.Object ref = guid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          guid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string guid = 3;</code>
       * @param value The bytes for guid to set.
       * @return This builder for chaining.
       */
      public Builder setGuidBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        guid_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string guid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGuid() {

        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }

      /**
       * <code>string rawRecord = 4;</code>
       * @return The rawRecord.
       */
      public java.lang.String getRawRecord() {
        java.lang.Object ref = rawRecord_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rawRecord_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string rawRecord = 4;</code>
       * @param value The rawRecord to set.
       * @return This builder for chaining.
       */
      public Builder setRawRecord(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        rawRecord_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string rawRecord = 4;</code>
       * @return The bytes for rawRecord.
       */
      public com.google.protobuf.ByteString
      getRawRecordBytes() {
        java.lang.Object ref = rawRecord_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          rawRecord_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string rawRecord = 4;</code>
       * @param value The bytes for rawRecord to set.
       * @return This builder for chaining.
       */
      public Builder setRawRecordBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        rawRecord_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string rawRecord = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRawRecord() {

        rawRecord_ = getDefaultInstance().getRawRecord();
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
