// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RawTransaction.proto

package com.ivyxjc.libra.core.models.protoModels;

public final class ProtoRawTransaction {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\024RawTransaction.proto\022(com.ivyxjc.libra" +
                        ".core.models.protoModels\"X\n\017PRawTransact" +
                        "ion\022\020\n\010sourceId\030\001 \001(\005\022\020\n\010sequence\030\002 \001(\005\022" +
                        "\016\n\006gcGuid\030\003 \001(\t\022\021\n\trawRecord\030\004 \001(\tB\025B\023Pr" +
                        "otoRawTransactionb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor,
                new java.lang.String[]{"SourceId", "Sequence", "GcGuid", "RawRecord",});
    }
    private ProtoRawTransaction() {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface PRawTransactionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 sourceId = 1;</code>
         *
         * @return The sourceId.
         */
        int getSourceId();

        /**
         * <code>int32 sequence = 2;</code>
         *
         * @return The sequence.
         */
        int getSequence();

        /**
         * <code>string gcGuid = 3;</code>
         *
         * @return The gcGuid.
         */
        java.lang.String getGcGuid();

        /**
         * <code>string gcGuid = 3;</code>
         *
         * @return The bytes for gcGuid.
         */
        com.google.protobuf.ByteString
        getGcGuidBytes();

        /**
         * <code>string rawRecord = 4;</code>
         *
         * @return The rawRecord.
         */
        java.lang.String getRawRecord();

        /**
         * <code>string rawRecord = 4;</code>
         *
         * @return The bytes for rawRecord.
         */
        com.google.protobuf.ByteString
        getRawRecordBytes();
    }

    /**
     * Protobuf type {@code com.ivyxjc.libra.core.models.protoModels.PRawTransaction}
     */
    public static final class PRawTransaction extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
            PRawTransactionOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use PRawTransaction.newBuilder() to construct.
        private PRawTransaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PRawTransaction() {
            gcGuid_ = "";
            rawRecord_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new PRawTransaction();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private PRawTransaction(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            sourceId_ = input.readInt32();
                            break;
                        }
                        case 16: {

                            sequence_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            gcGuid_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            rawRecord_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final int SEQUENCE_FIELD_NUMBER = 2;
        // @@protoc_insertion_point(class_scope:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
        private static final com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction DEFAULT_INSTANCE;

        public static final int SOURCEID_FIELD_NUMBER = 1;
        private static final com.google.protobuf.Parser<PRawTransaction>
                PARSER = new com.google.protobuf.AbstractParser<PRawTransaction>() {
            @java.lang.Override
            public PRawTransaction parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PRawTransaction(input, extensionRegistry);
            }
        };

        /**
         * <code>int32 sourceId = 1;</code>
         *
         * @return The sourceId.
         */
        public int getSourceId() {
            return sourceId_;
        }

        static {
            DEFAULT_INSTANCE = new com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction();
        }
        private int sequence_;

        /**
         * <code>int32 sequence = 2;</code>
         *
         * @return The sequence.
         */
        public int getSequence() {
            return sequence_;
        }

        public static final int GCGUID_FIELD_NUMBER = 3;
        private volatile java.lang.Object gcGuid_;

        private int sourceId_;

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
        }

        public static final int RAWRECORD_FIELD_NUMBER = 4;
        private volatile java.lang.Object rawRecord_;

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (sourceId_ != 0) {
                output.writeInt32(1, sourceId_);
            }
            if (sequence_ != 0) {
                output.writeInt32(2, sequence_);
            }
            if (!getGcGuidBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gcGuid_);
            }
            if (!getRawRecordBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rawRecord_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (sourceId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, sourceId_);
            }
            if (sequence_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, sequence_);
            }
            if (!getGcGuidBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gcGuid_);
            }
            if (!getRawRecordBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rawRecord_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
            hash = (53 * hash) + getSourceId();
            hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
            hash = (53 * hash) + getSequence();
            hash = (37 * hash) + GCGUID_FIELD_NUMBER;
            hash = (53 * hash) + getGcGuid().hashCode();
            hash = (37 * hash) + RAWRECORD_FIELD_NUMBER;
            hash = (53 * hash) + getRawRecord().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder(com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<PRawTransaction> parser() {
            return PARSER;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.class, com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.Builder.class);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <code>string gcGuid = 3;</code>
         *
         * @return The gcGuid.
         */
        public java.lang.String getGcGuid() {
            java.lang.Object ref = gcGuid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                gcGuid_ = s;
                return s;
            }
        }

        /**
         * <code>string gcGuid = 3;</code>
         *
         * @return The bytes for gcGuid.
         */
        public com.google.protobuf.ByteString
        getGcGuidBytes() {
            java.lang.Object ref = gcGuid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                gcGuid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string rawRecord = 4;</code>
         *
         * @return The rawRecord.
         */
        public java.lang.String getRawRecord() {
            java.lang.Object ref = rawRecord_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                rawRecord_ = s;
                return s;
            }
        }

        /**
         * <code>string rawRecord = 4;</code>
         *
         * @return The bytes for rawRecord.
         */
        public com.google.protobuf.ByteString
        getRawRecordBytes() {
            java.lang.Object ref = rawRecord_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                rawRecord_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction)) {
                return super.equals(obj);
            }
            com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction other = (com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction) obj;

            if (getSourceId()
                    != other.getSourceId()) return false;
            if (getSequence()
                    != other.getSequence()) return false;
            if (!getGcGuid()
                    .equals(other.getGcGuid())) return false;
            if (!getRawRecord()
                    .equals(other.getRawRecord())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PRawTransaction> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code com.ivyxjc.libra.core.models.protoModels.PRawTransaction}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
                com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransactionOrBuilder {
            private int sourceId_;
            private int sequence_;

            // Construct using com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                sourceId_ = 0;

                sequence_ = 0;

                gcGuid_ = "";

                rawRecord_ = "";

                return this;
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.class, com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.Builder.class);
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
            }

            @java.lang.Override
            public com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction getDefaultInstanceForType() {
                return com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.getDefaultInstance();
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction build() {
                com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction buildPartial() {
                com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction result = new com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction(this);
                result.sourceId_ = sourceId_;
                result.sequence_ = sequence_;
                result.gcGuid_ = gcGuid_;
                result.rawRecord_ = rawRecord_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction) {
                    return mergeFrom((com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction other) {
                if (other == com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.getDefaultInstance())
                    return this;
                if (other.getSourceId() != 0) {
                    setSourceId(other.getSourceId());
                }
                if (other.getSequence() != 0) {
                    setSequence(other.getSequence());
                }
                if (!other.getGcGuid().isEmpty()) {
                    gcGuid_ = other.gcGuid_;
                    onChanged();
                }
                if (!other.getRawRecord().isEmpty()) {
                    rawRecord_ = other.rawRecord_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int32 sourceId = 1;</code>
             *
             * @return The sourceId.
             */
            public int getSourceId() {
                return sourceId_;
            }

            /**
             * <code>int32 sourceId = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSourceId() {

                sourceId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>int32 sourceId = 1;</code>
             *
             * @param value The sourceId to set.
             * @return This builder for chaining.
             */
            public Builder setSourceId(int value) {

                sourceId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 sequence = 2;</code>
             *
             * @return The sequence.
             */
            public int getSequence() {
                return sequence_;
            }

            /**
             * <code>int32 sequence = 2;</code>
             *
             * @param value The sequence to set.
             * @return This builder for chaining.
             */
            public Builder setSequence(int value) {

                sequence_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 sequence = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSequence() {

                sequence_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object gcGuid_ = "";

            /**
             * <code>string gcGuid = 3;</code>
             *
             * @return The gcGuid.
             */
            public java.lang.String getGcGuid() {
                java.lang.Object ref = gcGuid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    gcGuid_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string gcGuid = 3;</code>
             *
             * @return The bytes for gcGuid.
             */
            public com.google.protobuf.ByteString
            getGcGuidBytes() {
                java.lang.Object ref = gcGuid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    gcGuid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string gcGuid = 3;</code>
             *
             * @param value The gcGuid to set.
             * @return This builder for chaining.
             */
            public Builder setGcGuid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                gcGuid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string gcGuid = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearGcGuid() {

                gcGuid_ = getDefaultInstance().getGcGuid();
                onChanged();
                return this;
            }

            /**
             * <code>string gcGuid = 3;</code>
             *
             * @param value The bytes for gcGuid to set.
             * @return This builder for chaining.
             */
            public Builder setGcGuidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                gcGuid_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object rawRecord_ = "";

            /**
             * <code>string rawRecord = 4;</code>
             *
             * @return The rawRecord.
             */
            public java.lang.String getRawRecord() {
                java.lang.Object ref = rawRecord_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    rawRecord_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string rawRecord = 4;</code>
             *
             * @return The bytes for rawRecord.
             */
            public com.google.protobuf.ByteString
            getRawRecordBytes() {
                java.lang.Object ref = rawRecord_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    rawRecord_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string rawRecord = 4;</code>
             *
             * @param value The rawRecord to set.
             * @return This builder for chaining.
             */
            public Builder setRawRecord(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                rawRecord_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string rawRecord = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRawRecord() {

                rawRecord_ = getDefaultInstance().getRawRecord();
                onChanged();
                return this;
            }

            /**
             * <code>string rawRecord = 4;</code>
             *
             * @param value The bytes for rawRecord to set.
             * @return This builder for chaining.
             */
            public Builder setRawRecordBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                rawRecord_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
