// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RawTransaction.proto

package com.ivyxjc.libra.core.models.protoModels;

public final class ProtoRawTransaction {
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable;
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    String[] descriptorData = {
      "\n\024RawTransaction.proto\022(com.ivyxjc.libra" +
      ".core.models.protoModels\"\214\001\n\017PRawTransac" +
      "tion\022\014\n\004guid\030\001 \001(\t\022\020\n\010sourceId\030\002 \001(\005\022\020\n\010" +
      "sequence\030\003 \001(\003\022\r\n\005msgId\030\004 \001(\t\022\017\n\007version" +
      "\030\005 \001(\005\022\024\n\014duplicateFlg\030\006 \001(\005\022\021\n\trawRecor" +
      "d\030\007 \001(\tB\025B\023ProtoRawTransactionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor,
        new String[] { "Guid", "SourceId", "Sequence", "MsgId", "Version", "DuplicateFlg", "RawRecord", });
  }
  private ProtoRawTransaction() {}

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  public interface PRawTransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string guid = 1;</code>
     * @return The guid.
     */
    String getGuid();
    /**
     * <code>string guid = 1;</code>
     * @return The bytes for guid.
     */
    com.google.protobuf.ByteString
        getGuidBytes();

    /**
     * <code>int32 sourceId = 2;</code>
     * @return The sourceId.
     */
    int getSourceId();

    /**
     * <code>int64 sequence = 3;</code>
     * @return The sequence.
     */
    long getSequence();

    /**
     * <code>string msgId = 4;</code>
     * @return The msgId.
     */
    String getMsgId();
    /**
     * <code>string msgId = 4;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>int32 version = 5;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>int32 duplicateFlg = 6;</code>
     * @return The duplicateFlg.
     */
    int getDuplicateFlg();

    /**
     * <code>string rawRecord = 7;</code>
     * @return The rawRecord.
     */
    String getRawRecord();
    /**
     * <code>string rawRecord = 7;</code>
     * @return The bytes for rawRecord.
     */
    com.google.protobuf.ByteString
        getRawRecordBytes();
  }

  /**
   * Protobuf type {@code com.ivyxjc.libra.core.models.protoModels.PRawTransaction}
   */
  public  static final class PRawTransaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
      PRawTransactionOrBuilder {
    public static final int GUID_FIELD_NUMBER = 1;
    // Use PRawTransaction.newBuilder() to construct.
    private PRawTransaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    public static final int SOURCEID_FIELD_NUMBER = 2;
    public static final int SEQUENCE_FIELD_NUMBER = 3;
    public static final int MSGID_FIELD_NUMBER = 4;
    public static final int VERSION_FIELD_NUMBER = 5;
    public static final int DUPLICATEFLG_FIELD_NUMBER = 6;
    public static final int RAWRECORD_FIELD_NUMBER = 7;
  private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
    private static final PRawTransaction DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<PRawTransaction>
        PARSER = new com.google.protobuf.AbstractParser<PRawTransaction>() {
      @Override
      public PRawTransaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PRawTransaction(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new PRawTransaction();
    }

    private volatile Object guid_;
    private int sourceId_;
    private long sequence_;
    private volatile Object msgId_;
    private int version_;
    private int duplicateFlg_;
    private volatile Object rawRecord_;
    private byte memoizedIsInitialized = -1;
    private PRawTransaction() {
      guid_ = "";
      msgId_ = "";
      rawRecord_ = "";
    }
    private PRawTransaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              guid_ = s;
              break;
            }
            case 16: {

              sourceId_ = input.readInt32();
              break;
            }
            case 24: {

              sequence_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            case 40: {

              version_ = input.readInt32();
              break;
            }
            case 48: {

              duplicateFlg_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              rawRecord_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
    }

    public static PRawTransaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PRawTransaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PRawTransaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PRawTransaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PRawTransaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PRawTransaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PRawTransaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static PRawTransaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PRawTransaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PRawTransaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static PRawTransaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static PRawTransaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(PRawTransaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static PRawTransaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<PRawTransaction> parser() {
      return PARSER;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PRawTransaction();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PRawTransaction.class, Builder.class);
    }

    /**
     * <code>string guid = 1;</code>
     * @return The guid.
     */
    public String getGuid() {
      Object ref = guid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        guid_ = s;
        return s;
      }
    }

    /**
     * <code>string guid = 1;</code>
     * @return The bytes for guid.
     */
    public com.google.protobuf.ByteString
        getGuidBytes() {
      Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>int32 sourceId = 2;</code>
     * @return The sourceId.
     */
    public int getSourceId() {
      return sourceId_;
    }

    /**
     * <code>int64 sequence = 3;</code>
     * @return The sequence.
     */
    public long getSequence() {
      return sequence_;
    }

    /**
     * <code>string msgId = 4;</code>
     * @return The msgId.
     */
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }

    /**
     * <code>string msgId = 4;</code>
     * @return The bytes for msgId.
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>int32 version = 5;</code>
     * @return The version.
     */
    public int getVersion() {
      return version_;
    }

    /**
     * <code>int32 duplicateFlg = 6;</code>
     * @return The duplicateFlg.
     */
    public int getDuplicateFlg() {
      return duplicateFlg_;
    }

    /**
     * <code>string rawRecord = 7;</code>
     * @return The rawRecord.
     */
    public String getRawRecord() {
      Object ref = rawRecord_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rawRecord_ = s;
        return s;
      }
    }

    /**
     * <code>string rawRecord = 7;</code>
     * @return The bytes for rawRecord.
     */
    public com.google.protobuf.ByteString
        getRawRecordBytes() {
      Object ref = rawRecord_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rawRecord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, guid_);
      }
      if (sourceId_ != 0) {
        output.writeInt32(2, sourceId_);
      }
      if (sequence_ != 0L) {
        output.writeInt64(3, sequence_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msgId_);
      }
      if (version_ != 0) {
        output.writeInt32(5, version_);
      }
      if (duplicateFlg_ != 0) {
        output.writeInt32(6, duplicateFlg_);
      }
      if (!getRawRecordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, rawRecord_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, guid_);
      }
      if (sourceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sourceId_);
      }
      if (sequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sequence_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msgId_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, version_);
      }
      if (duplicateFlg_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, duplicateFlg_);
      }
      if (!getRawRecordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, rawRecord_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PRawTransaction)) {
        return super.equals(obj);
      }
      PRawTransaction other = (PRawTransaction) obj;

      if (!getGuid()
          .equals(other.getGuid())) return false;
      if (getSourceId()
          != other.getSourceId()) return false;
      if (getSequence()
          != other.getSequence()) return false;
      if (!getMsgId()
          .equals(other.getMsgId())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (getDuplicateFlg()
          != other.getDuplicateFlg()) return false;
      if (!getRawRecord()
          .equals(other.getRawRecord())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GUID_FIELD_NUMBER;
      hash = (53 * hash) + getGuid().hashCode();
      hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
      hash = (53 * hash) + getSourceId();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequence());
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + DUPLICATEFLG_FIELD_NUMBER;
      hash = (53 * hash) + getDuplicateFlg();
      hash = (37 * hash) + RAWRECORD_FIELD_NUMBER;
      hash = (53 * hash) + getRawRecord().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @Override
    public com.google.protobuf.Parser<PRawTransaction> getParserForType() {
      return PARSER;
    }

    @Override
    public PRawTransaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.ivyxjc.libra.core.models.protoModels.PRawTransaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
        PRawTransactionOrBuilder {
      private Object guid_ = "";
      private int sourceId_ ;

      // Construct using com.ivyxjc.libra.core.models.protoModels.ProtoRawTransaction.PRawTransaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      private long sequence_ ;
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      private Object msgId_ = "";
      private int version_ ;
      private int duplicateFlg_ ;
      private Object rawRecord_ = "";

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PRawTransaction.class, Builder.class);
      }

      @Override
      public Builder clear() {
        super.clear();
        guid_ = "";

        sourceId_ = 0;

        sequence_ = 0L;

        msgId_ = "";

        version_ = 0;

        duplicateFlg_ = 0;

        rawRecord_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoRawTransaction.internal_static_com_ivyxjc_libra_core_models_protoModels_PRawTransaction_descriptor;
      }

      @Override
      public PRawTransaction getDefaultInstanceForType() {
        return PRawTransaction.getDefaultInstance();
      }

      @Override
      public PRawTransaction build() {
        PRawTransaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PRawTransaction buildPartial() {
        PRawTransaction result = new PRawTransaction(this);
        result.guid_ = guid_;
        result.sourceId_ = sourceId_;
        result.sequence_ = sequence_;
        result.msgId_ = msgId_;
        result.version_ = version_;
        result.duplicateFlg_ = duplicateFlg_;
        result.rawRecord_ = rawRecord_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }

      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }

      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PRawTransaction) {
          return mergeFrom((PRawTransaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PRawTransaction other) {
        if (other == PRawTransaction.getDefaultInstance()) return this;
        if (!other.getGuid().isEmpty()) {
          guid_ = other.guid_;
          onChanged();
        }
        if (other.getSourceId() != 0) {
          setSourceId(other.getSourceId());
        }
        if (other.getSequence() != 0L) {
          setSequence(other.getSequence());
        }
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getDuplicateFlg() != 0) {
          setDuplicateFlg(other.getDuplicateFlg());
        }
        if (!other.getRawRecord().isEmpty()) {
          rawRecord_ = other.rawRecord_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PRawTransaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PRawTransaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>string guid = 1;</code>
       * @return The guid.
       */
      public String getGuid() {
        Object ref = guid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>string guid = 1;</code>
       * @param value The guid to set.
       * @return This builder for chaining.
       */
      public Builder setGuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        guid_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string guid = 1;</code>
       * @return The bytes for guid.
       */
      public com.google.protobuf.ByteString
          getGuidBytes() {
        Object ref = guid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          guid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string guid = 1;</code>
       * @param value The bytes for guid to set.
       * @return This builder for chaining.
       */
      public Builder setGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        guid_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string guid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGuid() {

        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }

      /**
       * <code>int32 sourceId = 2;</code>
       * @return The sourceId.
       */
      public int getSourceId() {
        return sourceId_;
      }

      /**
       * <code>int32 sourceId = 2;</code>
       * @param value The sourceId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceId(int value) {

        sourceId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 sourceId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceId() {

        sourceId_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>int64 sequence = 3;</code>
       * @return The sequence.
       */
      public long getSequence() {
        return sequence_;
      }

      /**
       * <code>int64 sequence = 3;</code>
       * @param value The sequence to set.
       * @return This builder for chaining.
       */
      public Builder setSequence(long value) {

        sequence_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int64 sequence = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequence() {

        sequence_ = 0L;
        onChanged();
        return this;
      }

      /**
       * <code>string msgId = 4;</code>
       * @return The msgId.
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>string msgId = 4;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        msgId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string msgId = 4;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string msgId = 4;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        msgId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string msgId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {

        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }

      /**
       * <code>int32 version = 5;</code>
       * @return The version.
       */
      public int getVersion() {
        return version_;
      }

      /**
       * <code>int32 version = 5;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {

        version_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 version = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {

        version_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>int32 duplicateFlg = 6;</code>
       * @return The duplicateFlg.
       */
      public int getDuplicateFlg() {
        return duplicateFlg_;
      }

      /**
       * <code>int32 duplicateFlg = 6;</code>
       * @param value The duplicateFlg to set.
       * @return This builder for chaining.
       */
      public Builder setDuplicateFlg(int value) {

        duplicateFlg_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 duplicateFlg = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDuplicateFlg() {

        duplicateFlg_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>string rawRecord = 7;</code>
       * @return The rawRecord.
       */
      public String getRawRecord() {
        Object ref = rawRecord_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rawRecord_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>string rawRecord = 7;</code>
       * @param value The rawRecord to set.
       * @return This builder for chaining.
       */
      public Builder setRawRecord(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        rawRecord_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string rawRecord = 7;</code>
       * @return The bytes for rawRecord.
       */
      public com.google.protobuf.ByteString
          getRawRecordBytes() {
        Object ref = rawRecord_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rawRecord_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string rawRecord = 7;</code>
       * @param value The bytes for rawRecord to set.
       * @return This builder for chaining.
       */
      public Builder setRawRecordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        rawRecord_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string rawRecord = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRawRecord() {

        rawRecord_ = getDefaultInstance().getRawRecord();
        onChanged();
        return this;
      }

      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ivyxjc.libra.core.models.protoModels.PRawTransaction)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
