// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UseCaseTxn.proto

package xyz.ivyxjc.libra.core.models.protoModels;

public final class ProtoUsecaseTxn {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_descriptor;

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_AttributesEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_AttributesEntry_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020UseCaseTxn.proto\022(xyz.ivyxjc.libra.cor" +
                        "e.models.protoModels\"\316\001\n\013PUseCaseTxn\022\020\n\010" +
                        "sourceId\030\001 \001(\005\022\016\n\006gcGuid\030\002 \001(\t\022\017\n\007ucTxnI" +
                        "d\030\003 \001(\005\022Y\n\nattributes\030\004 \003(\0132E.xyz.ivyxjc" +
                        ".libra.core.models.protoModels.PUseCaseT" +
                        "xn.AttributesEntry\0321\n\017AttributesEntry\022\013\n" +
                        "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\021B\017ProtoUs" +
                        "ecaseTxnb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_descriptor,
                new java.lang.String[]{"SourceId", "GcGuid", "UcTxnId", "Attributes",});
        internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_AttributesEntry_descriptor =
                internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_descriptor.getNestedTypes().get(0);
        internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_AttributesEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_AttributesEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
    }
    private ProtoUsecaseTxn() {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface PUseCaseTxnOrBuilder extends
            // @@protoc_insertion_point(interface_extends:xyz.ivyxjc.libra.core.models.protoModels.PUseCaseTxn)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 sourceId = 1;</code>
         *
         * @return The sourceId.
         */
        int getSourceId();

        /**
         * <code>string gcGuid = 2;</code>
         *
         * @return The gcGuid.
         */
        java.lang.String getGcGuid();

        /**
         * <code>string gcGuid = 2;</code>
         *
         * @return The bytes for gcGuid.
         */
        com.google.protobuf.ByteString
        getGcGuidBytes();

        /**
         * <code>int32 ucTxnId = 3;</code>
         *
         * @return The ucTxnId.
         */
        int getUcTxnId();

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */
        int getAttributesCount();

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */
        boolean containsAttributes(
                java.lang.String key);

        /**
         * Use {@link #getAttributesMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String>
        getAttributes();

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */
        java.util.Map<java.lang.String, java.lang.String>
        getAttributesMap();

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        java.lang.String getAttributesOrDefault(
                java.lang.String key,
                java.lang.String defaultValue);

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        java.lang.String getAttributesOrThrow(
                java.lang.String key);
    }

    /**
     * Protobuf type {@code xyz.ivyxjc.libra.core.models.protoModels.PUseCaseTxn}
     */
    public static final class PUseCaseTxn extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:xyz.ivyxjc.libra.core.models.protoModels.PUseCaseTxn)
            PUseCaseTxnOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use PUseCaseTxn.newBuilder() to construct.
        private PUseCaseTxn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PUseCaseTxn() {
            gcGuid_ = "";
        }

        public static final int SOURCEID_FIELD_NUMBER = 1;
        public static final int GCGUID_FIELD_NUMBER = 2;

        private PUseCaseTxn(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            sourceId_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            gcGuid_ = s;
                            break;
                        }
                        case 24: {

                            ucTxnId_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                attributes_ = com.google.protobuf.MapField.newMapField(
                                        AttributesDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                    attributes__ = input.readMessage(
                                    AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            attributes_.getMutableMap().put(
                                    attributes__.getKey(), attributes__.getValue());
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final int UCTXNID_FIELD_NUMBER = 3;
        public static final int ATTRIBUTES_FIELD_NUMBER = 4;
        // @@protoc_insertion_point(class_scope:xyz.ivyxjc.libra.core.models.protoModels.PUseCaseTxn)
        private static final xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<PUseCaseTxn>
                PARSER = new com.google.protobuf.AbstractParser<PUseCaseTxn>() {
            @java.lang.Override
            public PUseCaseTxn parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PUseCaseTxn(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn();
        }

        /**
         * <code>int32 sourceId = 1;</code>
         *
         * @return The sourceId.
         */
        public int getSourceId() {
            return sourceId_;
        }

        private int sourceId_;
        private volatile java.lang.Object gcGuid_;
        private int ucTxnId_;
        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> attributes_;
        private byte memoizedIsInitialized = -1;

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_descriptor;
        }

        /**
         * <code>int32 ucTxnId = 3;</code>
         *
         * @return The ucTxnId.
         */
        public int getUcTxnId() {
            return ucTxnId_;
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (sourceId_ != 0) {
                output.writeInt32(1, sourceId_);
            }
            if (!getGcGuidBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gcGuid_);
            }
            if (ucTxnId_ != 0) {
                output.writeInt32(3, ucTxnId_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetAttributes(),
                            AttributesDefaultEntryHolder.defaultEntry,
                            4);
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (sourceId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, sourceId_);
            }
            if (!getGcGuidBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gcGuid_);
            }
            if (ucTxnId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, ucTxnId_);
            }
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetAttributes().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, attributes__);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
            hash = (53 * hash) + getSourceId();
            hash = (37 * hash) + GCGUID_FIELD_NUMBER;
            hash = (53 * hash) + getGcGuid().hashCode();
            hash = (37 * hash) + UCTXNID_FIELD_NUMBER;
            hash = (53 * hash) + getUcTxnId();
            if (!internalGetAttributes().getMap().isEmpty()) {
                hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
                hash = (53 * hash) + internalGetAttributes().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Builder newBuilder(xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<PUseCaseTxn> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new PUseCaseTxn();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 4:
                    return internalGetAttributes();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn.class, xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn.Builder.class);
        }

        /**
         * <code>string gcGuid = 2;</code>
         *
         * @return The gcGuid.
         */
        public java.lang.String getGcGuid() {
            java.lang.Object ref = gcGuid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                gcGuid_ = s;
                return s;
            }
        }

        /**
         * <code>string gcGuid = 2;</code>
         *
         * @return The bytes for gcGuid.
         */
        public com.google.protobuf.ByteString
        getGcGuidBytes() {
            java.lang.Object ref = gcGuid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                gcGuid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetAttributes() {
            if (attributes_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        AttributesDefaultEntryHolder.defaultEntry);
            }
            return attributes_;
        }

        public int getAttributesCount() {
            return internalGetAttributes().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        public boolean containsAttributes(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetAttributes().getMap().containsKey(key);
        }

        /**
         * Use {@link #getAttributesMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
            return getAttributesMap();
        }

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
            return internalGetAttributes().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        public java.lang.String getAttributesOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetAttributes().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        public java.lang.String getAttributesOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetAttributes().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn)) {
                return super.equals(obj);
            }
            xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn other = (xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn) obj;

            if (getSourceId()
                    != other.getSourceId()) return false;
            if (!getGcGuid()
                    .equals(other.getGcGuid())) return false;
            if (getUcTxnId()
                    != other.getUcTxnId()) return false;
            if (!internalGetAttributes().equals(
                    other.internalGetAttributes())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PUseCaseTxn> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        private static final class AttributesDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_AttributesEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        /**
         * Protobuf type {@code xyz.ivyxjc.libra.core.models.protoModels.PUseCaseTxn}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:xyz.ivyxjc.libra.core.models.protoModels.PUseCaseTxn)
                xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxnOrBuilder {
            private int bitField0_;

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetAttributes();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMutableAttributes();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            private int sourceId_;
            private java.lang.Object gcGuid_ = "";
            private int ucTxnId_;

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> attributes_;

            // Construct using xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn.class, xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn.Builder.class);
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                sourceId_ = 0;

                gcGuid_ = "";

                ucTxnId_ = 0;

                internalGetMutableAttributes().clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.internal_static_xyz_ivyxjc_libra_core_models_protoModels_PUseCaseTxn_descriptor;
            }

            @java.lang.Override
            public xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn getDefaultInstanceForType() {
                return xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn.getDefaultInstance();
            }

            @java.lang.Override
            public xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn build() {
                xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn buildPartial() {
                xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn result = new xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn(this);
                int from_bitField0_ = bitField0_;
                result.sourceId_ = sourceId_;
                result.gcGuid_ = gcGuid_;
                result.ucTxnId_ = ucTxnId_;
                result.attributes_ = internalGetAttributes();
                result.attributes_.makeImmutable();
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn) {
                    return mergeFrom((xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            /**
             * <code>int32 sourceId = 1;</code>
             *
             * @return The sourceId.
             */
            public int getSourceId() {
                return sourceId_;
            }

            /**
             * <code>int32 sourceId = 1;</code>
             *
             * @param value The sourceId to set.
             * @return This builder for chaining.
             */
            public Builder setSourceId(int value) {

                sourceId_ = value;
                onChanged();
                return this;
            }

            public Builder mergeFrom(xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn other) {
                if (other == xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn.getDefaultInstance())
                    return this;
                if (other.getSourceId() != 0) {
                    setSourceId(other.getSourceId());
                }
                if (!other.getGcGuid().isEmpty()) {
                    gcGuid_ = other.gcGuid_;
                    onChanged();
                }
                if (other.getUcTxnId() != 0) {
                    setUcTxnId(other.getUcTxnId());
                }
                internalGetMutableAttributes().mergeFrom(
                        other.internalGetAttributes());
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (xyz.ivyxjc.libra.core.models.protoModels.ProtoUsecaseTxn.PUseCaseTxn) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int32 sourceId = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSourceId() {

                sourceId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string gcGuid = 2;</code>
             *
             * @return The gcGuid.
             */
            public java.lang.String getGcGuid() {
                java.lang.Object ref = gcGuid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    gcGuid_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string gcGuid = 2;</code>
             *
             * @param value The gcGuid to set.
             * @return This builder for chaining.
             */
            public Builder setGcGuid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                gcGuid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string gcGuid = 2;</code>
             *
             * @return The bytes for gcGuid.
             */
            public com.google.protobuf.ByteString
            getGcGuidBytes() {
                java.lang.Object ref = gcGuid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    gcGuid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string gcGuid = 2;</code>
             *
             * @param value The bytes for gcGuid to set.
             * @return This builder for chaining.
             */
            public Builder setGcGuidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                gcGuid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 ucTxnId = 3;</code>
             *
             * @return The ucTxnId.
             */
            public int getUcTxnId() {
                return ucTxnId_;
            }

            /**
             * <code>int32 ucTxnId = 3;</code>
             *
             * @param value The ucTxnId to set.
             * @return This builder for chaining.
             */
            public Builder setUcTxnId(int value) {

                ucTxnId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string gcGuid = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearGcGuid() {

                gcGuid_ = getDefaultInstance().getGcGuid();
                onChanged();
                return this;
            }

            /**
             * <code>int32 ucTxnId = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUcTxnId() {

                ucTxnId_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetAttributes() {
                if (attributes_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            AttributesDefaultEntryHolder.defaultEntry);
                }
                return attributes_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableAttributes() {
                onChanged();
                ;
                if (attributes_ == null) {
                    attributes_ = com.google.protobuf.MapField.newMapField(
                            AttributesDefaultEntryHolder.defaultEntry);
                }
                if (!attributes_.isMutable()) {
                    attributes_ = attributes_.copy();
                }
                return attributes_;
            }

            public int getAttributesCount() {
                return internalGetAttributes().getMap().size();
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public boolean containsAttributes(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                return internalGetAttributes().getMap().containsKey(key);
            }

            /**
             * Use {@link #getAttributesMap()} instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
                return getAttributesMap();
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
                return internalGetAttributes().getMap();
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public java.lang.String getAttributesOrDefault(
                    java.lang.String key,
                    java.lang.String defaultValue) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetAttributes().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public java.lang.String getAttributesOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetAttributes().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearAttributes() {
                internalGetMutableAttributes().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public Builder removeAttributes(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableAttributes().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableAttributes() {
                return internalGetMutableAttributes().getMutableMap();
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */
            public Builder putAttributes(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                if (value == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableAttributes().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public Builder putAllAttributes(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableAttributes().getMutableMap()
                        .putAll(values);
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:xyz.ivyxjc.libra.core.models.protoModels.PUseCaseTxn)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
