package xyz.ivyxjc.libra.core.models.protoModels;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UsecaseTxn.proto

@SuppressWarnings("all")
public final class ProtoUsecaseTxn {
    private ProtoUsecaseTxn() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface PUsecaseTxnOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PUsecaseTxn)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int64 sourceId = 1;</code>
         */
        long getSourceId();

        /**
         * <code>string gcGuid = 2;</code>
         */
        java.lang.String getGcGuid();

        /**
         * <code>string gcGuid = 2;</code>
         */
        com.google.protobuf.ByteString
        getGcGuidBytes();

        /**
         * <code>int64 ucTxnId = 3;</code>
         */
        long getUcTxnId();

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */
        int getAttributesCount();

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */
        boolean containsAttributes(
                java.lang.String key);

        /**
         * Use {@link #getAttributesMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String>
        getAttributes();

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */
        java.util.Map<java.lang.String, java.lang.String>
        getAttributesMap();

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        java.lang.String getAttributesOrDefault(
                java.lang.String key,
                java.lang.String defaultValue);

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        java.lang.String getAttributesOrThrow(
                java.lang.String key);
    }

    /**
     * Protobuf type {@code PUsecaseTxn}
     */
    public static final class PUsecaseTxn extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:PUsecaseTxn)
            PUsecaseTxnOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use PUsecaseTxn.newBuilder() to construct.
        private PUsecaseTxn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PUsecaseTxn() {
            gcGuid_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new PUsecaseTxn();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private PUsecaseTxn(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            sourceId_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            gcGuid_ = s;
                            break;
                        }
                        case 24: {

                            ucTxnId_ = input.readInt64();
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                attributes_ = com.google.protobuf.MapField.newMapField(
                                        AttributesDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                    attributes__ = input.readMessage(
                                    AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            attributes_.getMutableMap().put(
                                    attributes__.getKey(), attributes__.getValue());
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoUsecaseTxn.internal_static_PUsecaseTxn_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 4:
                    return internalGetAttributes();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoUsecaseTxn.internal_static_PUsecaseTxn_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ProtoUsecaseTxn.PUsecaseTxn.class, ProtoUsecaseTxn.PUsecaseTxn.Builder.class);
        }

        public static final int SOURCEID_FIELD_NUMBER = 1;
        private long sourceId_;

        /**
         * <code>int64 sourceId = 1;</code>
         */
        public long getSourceId() {
            return sourceId_;
        }

        public static final int GCGUID_FIELD_NUMBER = 2;
        private volatile java.lang.Object gcGuid_;

        /**
         * <code>string gcGuid = 2;</code>
         */
        public java.lang.String getGcGuid() {
            java.lang.Object ref = gcGuid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                gcGuid_ = s;
                return s;
            }
        }

        /**
         * <code>string gcGuid = 2;</code>
         */
        public com.google.protobuf.ByteString
        getGcGuidBytes() {
            java.lang.Object ref = gcGuid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                gcGuid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int UCTXNID_FIELD_NUMBER = 3;
        private long ucTxnId_;

        /**
         * <code>int64 ucTxnId = 3;</code>
         */
        public long getUcTxnId() {
            return ucTxnId_;
        }

        public static final int ATTRIBUTES_FIELD_NUMBER = 4;

        private static final class AttributesDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    ProtoUsecaseTxn.internal_static_PUsecaseTxn_AttributesEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> attributes_;

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetAttributes() {
            if (attributes_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        AttributesDefaultEntryHolder.defaultEntry);
            }
            return attributes_;
        }

        public int getAttributesCount() {
            return internalGetAttributes().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        public boolean containsAttributes(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetAttributes().getMap().containsKey(key);
        }

        /**
         * Use {@link #getAttributesMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
            return getAttributesMap();
        }

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
            return internalGetAttributes().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        public java.lang.String getAttributesOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetAttributes().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; attributes = 4;</code>
         */

        public java.lang.String getAttributesOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetAttributes().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (sourceId_ != 0L) {
                output.writeInt64(1, sourceId_);
            }
            if (!getGcGuidBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gcGuid_);
            }
            if (ucTxnId_ != 0L) {
                output.writeInt64(3, ucTxnId_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetAttributes(),
                            AttributesDefaultEntryHolder.defaultEntry,
                            4);
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (sourceId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, sourceId_);
            }
            if (!getGcGuidBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gcGuid_);
            }
            if (ucTxnId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, ucTxnId_);
            }
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetAttributes().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, attributes__);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ProtoUsecaseTxn.PUsecaseTxn)) {
                return super.equals(obj);
            }
            ProtoUsecaseTxn.PUsecaseTxn other = (ProtoUsecaseTxn.PUsecaseTxn) obj;

            if (getSourceId()
                    != other.getSourceId()) return false;
            if (!getGcGuid()
                    .equals(other.getGcGuid())) return false;
            if (getUcTxnId()
                    != other.getUcTxnId()) return false;
            if (!internalGetAttributes().equals(
                    other.internalGetAttributes())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getSourceId());
            hash = (37 * hash) + GCGUID_FIELD_NUMBER;
            hash = (53 * hash) + getGcGuid().hashCode();
            hash = (37 * hash) + UCTXNID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getUcTxnId());
            if (!internalGetAttributes().getMap().isEmpty()) {
                hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
                hash = (53 * hash) + internalGetAttributes().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ProtoUsecaseTxn.PUsecaseTxn parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ProtoUsecaseTxn.PUsecaseTxn prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code PUsecaseTxn}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PUsecaseTxn)
                ProtoUsecaseTxn.PUsecaseTxnOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoUsecaseTxn.internal_static_PUsecaseTxn_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetAttributes();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMutableAttributes();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoUsecaseTxn.internal_static_PUsecaseTxn_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ProtoUsecaseTxn.PUsecaseTxn.class, ProtoUsecaseTxn.PUsecaseTxn.Builder.class);
            }

            // Construct using ProtoUsecaseTxn.PUsecaseTxn.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                sourceId_ = 0L;

                gcGuid_ = "";

                ucTxnId_ = 0L;

                internalGetMutableAttributes().clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoUsecaseTxn.internal_static_PUsecaseTxn_descriptor;
            }

            @java.lang.Override
            public ProtoUsecaseTxn.PUsecaseTxn getDefaultInstanceForType() {
                return ProtoUsecaseTxn.PUsecaseTxn.getDefaultInstance();
            }

            @java.lang.Override
            public ProtoUsecaseTxn.PUsecaseTxn build() {
                ProtoUsecaseTxn.PUsecaseTxn result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public ProtoUsecaseTxn.PUsecaseTxn buildPartial() {
                ProtoUsecaseTxn.PUsecaseTxn result = new ProtoUsecaseTxn.PUsecaseTxn(this);
                int from_bitField0_ = bitField0_;
                result.sourceId_ = sourceId_;
                result.gcGuid_ = gcGuid_;
                result.ucTxnId_ = ucTxnId_;
                result.attributes_ = internalGetAttributes();
                result.attributes_.makeImmutable();
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ProtoUsecaseTxn.PUsecaseTxn) {
                    return mergeFrom((ProtoUsecaseTxn.PUsecaseTxn) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ProtoUsecaseTxn.PUsecaseTxn other) {
                if (other == ProtoUsecaseTxn.PUsecaseTxn.getDefaultInstance()) return this;
                if (other.getSourceId() != 0L) {
                    setSourceId(other.getSourceId());
                }
                if (!other.getGcGuid().isEmpty()) {
                    gcGuid_ = other.gcGuid_;
                    onChanged();
                }
                if (other.getUcTxnId() != 0L) {
                    setUcTxnId(other.getUcTxnId());
                }
                internalGetMutableAttributes().mergeFrom(
                        other.internalGetAttributes());
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ProtoUsecaseTxn.PUsecaseTxn parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ProtoUsecaseTxn.PUsecaseTxn) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private long sourceId_;

            /**
             * <code>int64 sourceId = 1;</code>
             */
            public long getSourceId() {
                return sourceId_;
            }

            /**
             * <code>int64 sourceId = 1;</code>
             */
            public Builder setSourceId(long value) {

                sourceId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 sourceId = 1;</code>
             */
            public Builder clearSourceId() {

                sourceId_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object gcGuid_ = "";

            /**
             * <code>string gcGuid = 2;</code>
             */
            public java.lang.String getGcGuid() {
                java.lang.Object ref = gcGuid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    gcGuid_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string gcGuid = 2;</code>
             */
            public com.google.protobuf.ByteString
            getGcGuidBytes() {
                java.lang.Object ref = gcGuid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    gcGuid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string gcGuid = 2;</code>
             */
            public Builder setGcGuid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                gcGuid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string gcGuid = 2;</code>
             */
            public Builder clearGcGuid() {

                gcGuid_ = getDefaultInstance().getGcGuid();
                onChanged();
                return this;
            }

            /**
             * <code>string gcGuid = 2;</code>
             */
            public Builder setGcGuidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                gcGuid_ = value;
                onChanged();
                return this;
            }

            private long ucTxnId_;

            /**
             * <code>int64 ucTxnId = 3;</code>
             */
            public long getUcTxnId() {
                return ucTxnId_;
            }

            /**
             * <code>int64 ucTxnId = 3;</code>
             */
            public Builder setUcTxnId(long value) {

                ucTxnId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 ucTxnId = 3;</code>
             */
            public Builder clearUcTxnId() {

                ucTxnId_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> attributes_;

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetAttributes() {
                if (attributes_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            AttributesDefaultEntryHolder.defaultEntry);
                }
                return attributes_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableAttributes() {
                onChanged();
                ;
                if (attributes_ == null) {
                    attributes_ = com.google.protobuf.MapField.newMapField(
                            AttributesDefaultEntryHolder.defaultEntry);
                }
                if (!attributes_.isMutable()) {
                    attributes_ = attributes_.copy();
                }
                return attributes_;
            }

            public int getAttributesCount() {
                return internalGetAttributes().getMap().size();
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public boolean containsAttributes(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                return internalGetAttributes().getMap().containsKey(key);
            }

            /**
             * Use {@link #getAttributesMap()} instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
                return getAttributesMap();
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
                return internalGetAttributes().getMap();
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public java.lang.String getAttributesOrDefault(
                    java.lang.String key,
                    java.lang.String defaultValue) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetAttributes().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public java.lang.String getAttributesOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetAttributes().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearAttributes() {
                internalGetMutableAttributes().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public Builder removeAttributes(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableAttributes().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableAttributes() {
                return internalGetMutableAttributes().getMutableMap();
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */
            public Builder putAttributes(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                if (value == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableAttributes().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; attributes = 4;</code>
             */

            public Builder putAllAttributes(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableAttributes().getMutableMap()
                        .putAll(values);
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:PUsecaseTxn)
        }

        // @@protoc_insertion_point(class_scope:PUsecaseTxn)
        private static final ProtoUsecaseTxn.PUsecaseTxn DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ProtoUsecaseTxn.PUsecaseTxn();
        }

        public static ProtoUsecaseTxn.PUsecaseTxn getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<PUsecaseTxn>
                PARSER = new com.google.protobuf.AbstractParser<PUsecaseTxn>() {
            @java.lang.Override
            public PUsecaseTxn parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PUsecaseTxn(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<PUsecaseTxn> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PUsecaseTxn> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public ProtoUsecaseTxn.PUsecaseTxn getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PUsecaseTxn_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PUsecaseTxn_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PUsecaseTxn_AttributesEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PUsecaseTxn_AttributesEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020UsecaseTxn.proto\"\245\001\n\013PUsecaseTxn\022\020\n\010so" +
                        "urceId\030\001 \001(\003\022\016\n\006gcGuid\030\002 \001(\t\022\017\n\007ucTxnId\030" +
                        "\003 \001(\003\0220\n\nattributes\030\004 \003(\0132\034.PUsecaseTxn." +
                        "AttributesEntry\0321\n\017AttributesEntry\022\013\n\003ke" +
                        "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\021B\017ProtoUseca" +
                        "seTxnb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_PUsecaseTxn_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_PUsecaseTxn_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PUsecaseTxn_descriptor,
                new java.lang.String[]{"SourceId", "GcGuid", "UcTxnId", "Attributes",});
        internal_static_PUsecaseTxn_AttributesEntry_descriptor =
                internal_static_PUsecaseTxn_descriptor.getNestedTypes().get(0);
        internal_static_PUsecaseTxn_AttributesEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PUsecaseTxn_AttributesEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
