spring:
    datasource:
        url: ${jdbc.url}
        username: ${jdbc.username}
        password: ${jdbc.password}
        hikari:
            maximum-pool-size: 18
mybatis:
    type-aliases-package: com.ivyxjc.libra.core.dao
    mapper-locations: classpath:mybatis/*.xml


libra:
    internal:
        mq:
            url: ${artemis.url}

