spring:
    datasource:
        url: ${jdbc.url}
        username: ${jdbc.username}
        password: ${jdbc.password}
        maximum-pool-size: 10
mybatis:
    type-aliases-package: xyz.ivyxjc.libra.core.dao
    mapper-locations: classpath:mybatis/*.xml


libra:
    internal:
        mq:
            url: ${artemis.url}

