//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.26 at 11:13:25 PM CST 
//


package com.ivyxjc.libra.starter.config.source.model.inner.xsds;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.ivyxjc.libra.starter.config.source.model.inner.xsds package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Processor_QNAME = new QName("source-config.xsd", "processor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ivyxjc.libra.starter.config.source.model.inner.xsds
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XsdSourceConfig }
     */
    public XsdSourceConfig createXsdSourceConfig() {
        return new XsdSourceConfig();
    }

    /**
     * Create an instance of {@link XsdLibraFlowConfig }
     */
    public XsdLibraFlowConfig createXsdLibraFlowConfig() {
        return new XsdLibraFlowConfig();
    }

    /**
     * Create an instance of {@link XsdDescription }
     */
    public XsdDescription createXsdDescription() {
        return new XsdDescription();
    }

    /**
     * Create an instance of {@link XsdQPrefix }
     */
    public XsdQPrefix createXsdQPrefix() {
        return new XsdQPrefix();
    }

    /**
     * Create an instance of {@link XsdProcessorType }
     */
    public XsdProcessorType createXsdProcessorType() {
        return new XsdProcessorType();
    }

    /**
     * Create an instance of {@link XsdSourceConfig.XsdUsecase }
     */
    public XsdSourceConfig.XsdUsecase createXsdSourceConfigXsdUsecase() {
        return new XsdSourceConfig.XsdUsecase();
    }

    /**
     * Create an instance of {@link XsdUsecaseConfig }
     */
    public XsdUsecaseConfig createXsdUsecaseConfig() {
        return new XsdUsecaseConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XsdProcessorType }{@code >}}
     */
    @XmlElementDecl(namespace = "source-config.xsd", name = "processor")
    public JAXBElement<XsdProcessorType> createProcessor(XsdProcessorType value) {
        return new JAXBElement<XsdProcessorType>(_Processor_QNAME, XsdProcessorType.class, null, value);
    }

}
