//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.26 at 11:13:25 PM CST 
//


package com.ivyxjc.libra.starter.config.source.model.inner.xsds;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{source-config.xsd}description" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{source-config.xsd}q-prefix"/&gt;
 *           &lt;element ref="{source-config.xsd}source-config"/&gt;
 *           &lt;element ref="{source-config.xsd}usecase-config"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "description",
        "qPrefixOrSourceConfigOrUsecaseConfig"
})
@XmlRootElement(name = "libra-flow-config")
public class XsdLibraFlowConfig {

    protected XsdDescription description;
    @XmlElements({
            @XmlElement(name = "q-prefix", type = XsdQPrefix.class),
            @XmlElement(name = "source-config", type = XsdSourceConfig.class),
            @XmlElement(name = "usecase-config", type = XsdUsecaseConfig.class)
    })
    protected List<Object> qPrefixOrSourceConfigOrUsecaseConfig;

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link XsdDescription }
     */
    public XsdDescription getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link XsdDescription }
     */
    public void setDescription(XsdDescription value) {
        this.description = value;
    }

    /**
     * Gets the value of the qPrefixOrSourceConfigOrUsecaseConfig property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qPrefixOrSourceConfigOrUsecaseConfig property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQPrefixOrSourceConfigOrUsecaseConfig().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XsdQPrefix }
     * {@link XsdSourceConfig }
     * {@link XsdUsecaseConfig }
     */
    public List<Object> getQPrefixOrSourceConfigOrUsecaseConfig() {
        if (qPrefixOrSourceConfigOrUsecaseConfig == null) {
            qPrefixOrSourceConfigOrUsecaseConfig = new ArrayList<Object>();
        }
        return this.qPrefixOrSourceConfigOrUsecaseConfig;
    }

}
