//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.26 at 11:13:25 PM CST 
//


package com.ivyxjc.libra.starter.config.source.model.inner.xsds;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{source-config.xsd}identifiedIntType"&gt;
 *       &lt;group ref="{source-config.xsd}sourceElements"/&gt;
 *       &lt;attribute name="q-prefix" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "description",
        "processorOrUsecase"
})
@XmlRootElement(name = "source-config")
public class XsdSourceConfig
        extends XsdIdentifiedIntType {

    protected XsdDescription description;
    @XmlElements({
            @XmlElement(name = "processor", type = XsdProcessorType.class),
            @XmlElement(name = "usecase", type = XsdSourceConfig.XsdUsecase.class)
    })
    protected List<Object> processorOrUsecase;
    @XmlAttribute(name = "q-prefix")
    protected String qPrefix;
    @XmlAttribute(name = "queue")
    protected String queue;

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link XsdDescription }
     */
    public XsdDescription getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link XsdDescription }
     */
    public void setDescription(XsdDescription value) {
        this.description = value;
    }

    /**
     * Gets the value of the processorOrUsecase property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processorOrUsecase property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessorOrUsecase().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XsdProcessorType }
     * {@link XsdSourceConfig.XsdUsecase }
     */
    public List<Object> getProcessorOrUsecase() {
        if (processorOrUsecase == null) {
            processorOrUsecase = new ArrayList<Object>();
        }
        return this.processorOrUsecase;
    }

    /**
     * Gets the value of the qPrefix property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQPrefix() {
        return qPrefix;
    }

    /**
     * Sets the value of the qPrefix property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQPrefix(String value) {
        this.qPrefix = value;
    }

    /**
     * Gets the value of the queue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQueue() {
        return queue;
    }

    /**
     * Sets the value of the queue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQueue(String value) {
        this.queue = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded"&gt;
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "id"
    })
    public static class XsdUsecase {

        protected List<String> id;

        /**
         * Gets the value of the id property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the id property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getId().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         */
        public List<String> getId() {
            if (id == null) {
                id = new ArrayList<String>();
            }
            return this.id;
        }

    }

}
