//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.11 at 11:41:35 PM CST 
//


package com.ivyxjc.libra.starter.config.source.model.inner.xsds;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for usecase-type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="usecase-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="simple"/&gt;
 *     &lt;enumeration value="status"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "usecase-type")
@XmlEnum
public enum XsdUsecaseType {

    @XmlEnumValue("simple")
    SIMPLE("simple"),
    @XmlEnumValue("status")
    STATUS("status");
    private final String value;

    XsdUsecaseType(String v) {
        value = v;
    }

    public static XsdUsecaseType fromValue(String v) {
        for (XsdUsecaseType c : XsdUsecaseType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
