//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.26 at 11:13:25 PM CST 
//


package com.ivyxjc.libra.starter.config.source.model.inner.xsds;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{source-config.xsd}identifiedType"&gt;
 *       &lt;group ref="{source-config.xsd}usecaseElements"/&gt;
 *       &lt;attribute name="type" use="required" type="{source-config.xsd}usecase-type" /&gt;
 *       &lt;attribute name="q-prefix" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "description",
        "processor"
})
@XmlRootElement(name = "usecase-config")
public class XsdUsecaseConfig
        extends XsdIdentifiedType {

    protected XsdDescription description;
    protected List<XsdProcessorType> processor;
    @XmlAttribute(name = "type", required = true)
    protected XsdUsecaseType type;
    @XmlAttribute(name = "q-prefix")
    protected String qPrefix;
    @XmlAttribute(name = "queue")
    protected String queue;

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link XsdDescription }
     */
    public XsdDescription getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link XsdDescription }
     */
    public void setDescription(XsdDescription value) {
        this.description = value;
    }

    /**
     * Gets the value of the processor property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processor property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XsdProcessorType }
     */
    public List<XsdProcessorType> getProcessor() {
        if (processor == null) {
            processor = new ArrayList<XsdProcessorType>();
        }
        return this.processor;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link XsdUsecaseType }
     */
    public XsdUsecaseType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link XsdUsecaseType }
     */
    public void setType(XsdUsecaseType value) {
        this.type = value;
    }

    /**
     * Gets the value of the qPrefix property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQPrefix() {
        return qPrefix;
    }

    /**
     * Sets the value of the qPrefix property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQPrefix(String value) {
        this.qPrefix = value;
    }

    /**
     * Gets the value of the queue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQueue() {
        return queue;
    }

    /**
     * Sets the value of the queue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQueue(String value) {
        this.queue = value;
    }

}
